name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install

    - name: Run download script
      run: node scripts/download.js

    - name: Run compile script
      run: node scripts/compile.js

    - name: Push to NPM
      run: npm publish --dry-run